### ISSUE TITLE
Proje terk mi edildi?

### ISSUE THREAD

**Issue by EmreSURK** [Pardus-Linux/pisi#2]
Selamlar,
Projede uzun zamandır hiçbir etkinlik görülmüyor.
Proje sonlandırıldı mı?

**Comment by sulincix** [comment]
pardus projesi 2013 yılından itibaren debian tabanlı olarak devam etmektedir.
Güncel projelere https://github.com/pardus üzerinden erişebilirsiniz.

Pisi kaynak kodu ise gönüllülerce çatallanıp geliştirilmeye devam etmektedir:
https://github.com/pisilinux/pisi
